import pandas as pd
df = pd.read_csv("survey_results_public.csv")
#print(df)
# print(df.describe())
# print(df.describe(include=['O']))
# print(df.describe(include=['O', '']))
# print(df.describe(include=['O', 'object']))
#print(df.shape)
#print(df.info())
# print(df.head(3))
# print(df.tail(3))
print(df.head())
# print(df.columns)
# print(df.loc[0:2, 'Country':'CompTotal'])
# print(df.sort_index())
# print(df.sort_index(ascending=False))
